run:
  timeout: 5m
linters:
  enable:
    - govet
    - staticcheck
    - unused
    - errcheck
    - gosimple
    - deadcode
    - gocritic
    - ineffassign
    - gofmt
    - goimports
    - revive
    - dupl
issues:
  exclude-rules:
    - path: _test.go
      text: 'should have comment'
