name: Linux/Windows Build
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17.5' # The Go version to download (if necessary) and use.
    - name: build
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt -y install gcc libc6-dev libx11-dev xorg-dev libxtst-dev libpng++-dev xcb libxcb-xkb-dev x11-xkb-utils
        sudo apt-get install -y libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev xsel xclip gcc-multilib libz-mingw-w64-dev gcc-mingw-w64
        sudo apt-get install -y gcc-aarch64-linux-gnu gccgo-aarch64-linux-gnu
        go get -d ./...
        #dirty work around
        sudo sed -i 's|geve == 0|geve|g' ~/go/pkg/mod/github.com/go-vgo/robotgo@v0.100.9/hook.go
        bash linux-build.bash
        cd bin
        for i in `ls` ; do tar cJf $i.tar.xz $i ; done
        wait
        cd ..
        find .
    - name: Upload win binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./bin/windows-amd64.tar.xz
        tag: ${{ github.ref }}
    - name: Upload linux binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./bin/linux-amd64.tar.xz
        tag: ${{ github.ref }}
