name: Mac Build 
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.23.0' # The Go version to download (if necessary) and use.
    - name: build
      shell: bash
      run: |
        uname -a
        go get -d ./...
        mac-build.bash
        cd bin
        for i in `ls` ; do tar cJf $i.tar.xz $i ; done
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: bin/*tar.xz
          